// <auto-generated />
using System;
using Candidates_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Candidates_Project.Migrations
{
    [DbContext(typeof(CandidatesContext))]
    partial class CandidatesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Candidates_Project.Model.Candidate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Sex");

                    b.Property<string>("Skype");

                    b.HasKey("ID");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("Candidates_Project.Model.Candidate_Language", b =>
                {
                    b.Property<int>("CandidateID");

                    b.Property<int>("LanguageID");

                    b.Property<string>("Level");

                    b.HasKey("CandidateID", "LanguageID");

                    b.ToTable("CandidateLanguage");
                });

            modelBuilder.Entity("Candidates_Project.Model.Candidate_School", b =>
                {
                    b.Property<int>("CandidatesID");

                    b.Property<int>("HighSchoolID");

                    b.Property<string>("Degree");

                    b.Property<DateTime>("From");

                    b.Property<DateTime>("To");

                    b.HasKey("CandidatesID", "HighSchoolID");

                    b.ToTable("Candidate_Schools");
                });

            modelBuilder.Entity("Candidates_Project.Model.Candidate_Skills", b =>
                {
                    b.Property<int>("CandidateID");

                    b.Property<int>("SkillsID");

                    b.Property<string>("Level");

                    b.Property<int>("Month");

                    b.HasKey("CandidateID", "SkillsID");

                    b.ToTable("Candidate_Skills");
                });

            modelBuilder.Entity("Candidates_Project.Model.HighSchool", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("HighSchools");
                });

            modelBuilder.Entity("Candidates_Project.Model.Language", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Candidates_Project.Model.Options", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CanRelocate");

                    b.Property<bool>("CanWorkInTheOffice");

                    b.Property<bool>("CanWorkRemotly");

                    b.HasKey("ID");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("Candidates_Project.Model.Skills", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
